### ISSUE TITLE
NoMethodError: undefined method `reverse_each' for nil:NilClass

### ISSUE THREAD

**Issue by dentarg** [avinashbot/redd#18]
Somehow `listing = send(meth, *args, **params)` ended up being `nil` for me at [redd/clients/base/stream.rb:64](https://github.com/avidw/redd/blob/598fe7fd3adbeba2d5be3272059d6dc6ad495c03/lib/redd/clients/base/stream.rb#L64) (exception caught with [Sentry](https://github.com/getsentry/raven-ruby)):

```
Stacktrace (most recent call first):

  redd/clients/base/stream.rb:64:in `block in stream'
    listing.reverse_each do |thing|
  redd/clients/base/stream.rb:58:in `loop'
    loop do
  redd/clients/base/stream.rb:58:in `stream'
    loop do
  /app/lib/reddit.rb:14:in `stream_urls'
    reddit.stream "get_#{sort}", "all" do |thing|
  /app/lib/reddit_provider.rb:22:in `run'
    reddit.stream_urls(sort) do |url|
  reddit-provider.rb:6:in `block in <main>'
    RedditProvider.new.run
  raven/base.rb:96:in `capture'
    yield
  reddit-provider.rb:5:in `<main>'
    Raven.capture do
```

My code using `#stream` (simplified):

``` ruby
reddit = Redd.it(:userless, id, secret, user_agent: USER_AGENT)
reddit.authorize!

reddit.stream "get_new", "all" do |thing|
  # do stuff
end
```

Any idea of what might gone wrong?

Looks like [redd/clients/base/utilities.rb:48](https://github.com/avidw/redd/blob/598fe7fd3adbeba2d5be3272059d6dc6ad495c03/lib/redd/clients/base/utilities.rb#L48) kicked in

``` ruby
return nil unless body.is_a?(Hash)
```

I wonder why `body` wasn't a Hash.

**Comment by avidw** [comment]
That's interesting. The body should almost always be a hash because all data is sent through a JSON parser. It appears the JSON parser couldn't find valid JSON and just sent the raw string through (it might be an error I haven't seen before).

I know this sounds like something a typical coder would say, but I've been using `#stream` and I couldn't reproduce it on my machine. One thing you might be able to try is monkey-patching the code and see what the error specifically is. Something like:

```ruby
require "redd"

module Redd
  module Clients
    class Base
      module Utilities
        def object_from_body(body)
          raise body unless body.is_a?(Hash)
          object = object_from_kind(body[:kind])
          flat = flatten_body(body)
          object.new(self, flat)
        end
      end
    end
  end
end

# ... the rest of your code ...
```

I'm sorry I can't find an immediate solution, but maybe you can help me :)

**Comment by dentarg** [comment]
Sure, I was suspecting you would ask this... :) So since last night I've been running a simple script locally (using another set of reddit credentials), using the streaming function in redd (in a while-true loop, so it starts again if it crashes). So far I haven't seen this error, and it hasn't happened in production again (but it has occurred a total of three times in production).

This might be a bit off-topic... but I saw some other errors occur. The most notable being `Redd::Error::InvalidOAuth2Credentials` (http status code 401). It seems like it happens once every hour when streaming (screenshot from Sentry for production):

![image](https://cloud.githubusercontent.com/assets/42626/7456528/6094f76e-f285-11e4-983d-36a22e665711.png)

I also saw one `Redd::Error::BadRequest` (http status code 400) and one `Redd::Error::ServiceUnavailable` (http status code 503). The streaming method do ignore the 503, but I think it happened during authorization, that's why I saw it. Maybe I should open up other issues about these.

**Comment by dentarg** [comment]
But I think I should take your monkey patch and put it into production, then I can report back when it occurs. :)

**Comment by dentarg** [comment]
Some additional info (which might be useless)

The 503 is from CloudFlare, extracted from the HTML response:

```
<h2>our cdn was unable to reach our servers</h2>
<h1>Web server is returning an unknown error</h1>
There is an unknown connection issue between CloudFlare and the origin web server.
```

And the 400 response didn't include any additional information why the request was bad :( Just:

````
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>
````

**Comment by dentarg** [comment]
@avidw are you running the streaming method 24/7 somewhere? :)

**Comment by avidw** [comment]
I used to run stream 24/7, but not anymore. The 500 errors are on reddit's side, so I can't do much about that. The 400 error seems like a problem, but I don't know why it's firing. I'll start running the stream method for longer to see if I can find something.

The 401 error, on the other hand, I can diagnose. The error pops up because the session expires every hour. A simple line of code can fix it. I would put that line of code directly in the stream method, but I was worried about repeat requests and possibly IP bans if the `Access` object wasn't properly constructed.

```ruby
reddit.refresh_access! if reddit.access.expired?
# ... more code ...
```

If you do find more info on the original error, I'd love to hear it. I'll leave the issue open for now.

**Comment by dentarg** [comment]
I have the monkey patch in production now. I did happen one more time before I made the deploy, so it has happened a total of 4 times. :) Will report back how it goes.

**Comment by dentarg** [comment]
Still hasn't happened again, but I'm continuing to monitor for it.

**Comment by avidw** [comment]
Sorry about the lack of communication, exam season. I'll get back to the gem in a week or so.

**Comment by dentarg** [comment]
Sure, no problem at all, I understand.

**Comment by dentarg** [comment]
> Still hasn't happened again, but I'm continuing to monitor for it.

Oh, it has happened... but I have missed it, because, `raise body` makes the exception so large, so [Sentry](https://getsentry.com/) rejects it ("413 Request Entity Too Large"). But I just spotted it in the logs (lucky me).

Here is the logs with the exception: https://gist.githubusercontent.com/dentarg/ef4f943091e98ca3c021/raw/2a70baabba1c6a4e879dbb55e5a2ea34c8334a4b/redd-issue-18.txt

It's an CloudFlare error response

> There is an unknown connection issue between CloudFlare and the origin web server. As a result, the web page can not be displayed.
