### ISSUE TITLE
How to get full listing for #get_submitted?

### ISSUE THREAD

**Issue by sunwooz** [avinashbot/redd#38]
How can i set it up so #get_submitted brings back every result without limits. Is 100 the highest?

**Comment by cubadomingo** [comment]
From the Docs it states that you are able to pass a limit argument to get_submitted in which the value can be a number from 1 to 100.

> :limit (1..100) — The maximum number of things to return.

So 100 is the highest limit.

**Comment by lemtzas** [comment]
Can't look at it right now. But if there's an 'after' param you can use
that and loop. Won't apparently get EVERYTHING though - I think I found it
to cap around 10k posts when scanning users. Reddit API limitation, I
assume.
